services:
  - type: web
    name: cricketlive-pro-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_KEY
        value: cricketlive2026
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/backend/serviceAccount.json